version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    build: ./mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
     - 3306:3306